version: '3.9'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=parolotsql
      - POSTGRES_DB=locations
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    image: piichu24/locationip-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/locations",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "parolotsql",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

volumes:
  db: